extract_items_from_image:
  description: >
    Read an image file from the folder `src/order_processor/input` and extract product information related to hardware or machine tools. 
    The task involves identifying:
    - Product names (handwritten or printed)
    - Quantities requested

    Focus on accurately interpreting both handwritten and printed text, leveraging the capabilities of Google Gemini 2.5 Flash to ensure high accuracy in extraction.

  expected_input: >
    An image file containing a customer order located in the folder `src/order_processor/input`.

  expected_output: >
    A structured list of extracted items, including:
    - Product name
    - Quantity requested

  agent: order_image_reader
